-- Run this in pgAdmin on your crm_predictif_db database

-- 1. Automation rules defined by marketing
CREATE TABLE IF NOT EXISTS automation_rules (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(30)  NOT NULL
                      CHECK (type IN ('score_threshold', 'inactivity')),
    threshold       FLOAT,          -- used when type = 'score_threshold'
    inactivity_days INTEGER,        -- used when type = 'inactivity'
    action          VARCHAR(30)  NOT NULL DEFAULT 'notify'
                      CHECK (action IN ('notify', 'email', 'both')),
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. In-app notifications generated by the scheduler
CREATE TABLE IF NOT EXISTS notifications (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    lead_id     UUID REFERENCES leads(id) ON DELETE CASCADE,
    rule_id     UUID REFERENCES automation_rules(id) ON DELETE SET NULL,
    message     TEXT        NOT NULL,
    type        VARCHAR(20) NOT NULL DEFAULT 'info'
                  CHECK (type IN ('info', 'warning', 'success')),
    is_read     BOOLEAN     NOT NULL DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_is_read  ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_lead_id  ON notifications(lead_id);
